### ISSUE TITLE
Pulsante rosso

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/spid-sp-access-button#13]
Ciao,
Non capisco come mai il pulsante mi appare rosso
![immagine](https://user-images.githubusercontent.com/20642463/49999515-58d07080-ff97-11e8-9a1f-3ceb6afb7857.png)
`.button-spid{background-color:#AA0000;color:#FFF}`

Mi sfugge qualcosa?

**Comment by michaeldisaro** [comment]
Rispondo in ritardo per chi dovesse leggere: Il pulsante è rosso se si usa quello la cartella "Development"
