### ISSUE TITLE
Font Google

### ISSUE THREAD

**Issue by lvps** [italia/spid-sp-access-button#3]
Il file css importa i font dalla CDN di Google, che notoriamente viene utilizzata per tracciare gli utenti. Non e' esattamente una best practice, diciamo: si puo' fare qualcosa a riguardo (e.g. non usare la CDN)?

**Comment by umbros** [comment]
Ivps si grazie della segnalazione. Provvedo a rilasciare la modifica.

**Comment by mauromol** [comment]
@umbros ad oggi ancora non è stato fatto nulla a riguardo, giusto?

**Comment by worbas** [comment]
Probabilmente è un residuo dopo la prima bonifica del2017. E' rimaso un @import nel file **spid-sp-access-button.min.css**

**Comment by peppelinux** [comment]
Cari se potete e quando potete fare una PR per questo sarà mia cura unirla asap in master branch

**Comment by nunzionapoli** [comment]
Dovrebbe essere stato chiuso dalla PR https://github.com/italia/spid-sp-access-button/pull/26
