### ISSUE TITLE
Origine immagini bottoni con la creazione dinamica lista IDP

### ISSUE THREAD

**Issue by MdreW** [italia/spid-sp-access-button#31]
Nel json utilizzato per la creazione dinamica della lista degli IDP ( https://registry.spid.gov.it/entities-idp?&output=json&custom=info_display_base ) le immagini dei loghi vengono scaricati da questo repository.  
esempio della prima riga del json:
```
{
"entity_id":"https://id.lepida.it/idp/shibboleth",
"organization_name":"Lepida S.p.A.",
"logo_uri":"https://raw.githubusercontent.com/italia/spid-graphics/master/idp-logos/spid-idp-lepidaid.svg",
"registry_link":"https://registry.spid.gov.it/entities-idp/https%3A%2F%2Fid.lepida.it%2Fidp%2Fshibboleth?output=json"
}
```
E` una scelta voluta o un errore? Il download dei file raw tramite Github non è particolarmente veloce...

**Comment by damikael** [comment]
Grazie per la segnalazione @MdreW.
I loghi sono ora recuperati da CDN.
