### ISSUE TITLE
Infocamere

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/spid-sp-access-button#35]
Buongiorno, 
da oggi dovrebbe essere operativo il nuovo IDP infocamere, non trovo però il logo pubblicato nel progetto.
Nemmeno nella lista degli IDP è disponibile: https://registry.spid.gov.it/entities-idp?&output=json
Grazie.

**Comment by damikael** [comment]
Il logo e la entry nella lista degli IdP sulla API di registro sono ora disponibili
