### ISSUE TITLE
Uniformita' UI/UX pulsanti di login

### ISSUE THREAD

**Issue by alessandro-aglietti** [italia/spid-sp-access-button#4]
Guardando la cartella dei pulsanti 

https://github.com/italia/spid-sp-access-button/tree/master/src/img

deduco che non vedremo un classico pulsante unico a giro per tutti i siti tipo "login con facebook" ma ognuno se lo brandizzera' come meglio crede?

**Comment by umbros** [comment]
Per ora no ma è un'opzione su cui sto lavorando.
