### ISSUE TITLE
Se effettuo la chiamata con il parametro output=json ricevo un errore CORS

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-sp-access-button#45]
Nel caso faccia la chiamata al servizio via javascript con solo il parametro output:

`https://registry.spid.gov.it/entities-idp?output=json`

ricevo l'errore "blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", impedendomi di chiamare l'API per ricevere la lsita degli idp con il campo code.

Mentre questa chiamata, sintetica

https://registry.spid.gov.it/entities-idp?output=json&custom=info_display_base

l'header 'Access-Control-Allow-Origin': * è presente

**Comment by damikael** [comment]
Buongiorno @marco-maroni-spot-software ,
il problema dovrebbe ora essere risolto.
Attendo conferma.

Saluti,
Michele D'Amico (damikael)

**Comment by marco-maroni-spot-software** [comment]
Si confermo grazie mille problema risolto!
