### ISSUE TITLE
Piano di rilascio dei vari loghi sotto licenza di contenuto libero?

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-sp-access-button#5]
Discussione qui:

https://forum.italia.it/t/piano-di-rilascio-dei-vari-loghi-degli-idp-sotto-licenza-di-contenuto-libero/682

## Preambolo
Vi è un problema di natura legale da sistemare:

* Assumendo che dato che i principali CMS (WordPress, Joomla!, Drupal) sono protetti da una licenza di software libero copyleft (rispettivamente [GNU GPL V2+](https://www.gnu.org/licenses/gpl-2.0.html), v2 e v2+) ogni plugin distribuito per tali CMS deve essere protetto da una licenza compatibile con la GNU GPL v2+
* Assumendo che tali plugin SPID dovranno avere per forza di cose i vari loghi dei vari IDP

Sorge il problema, perchè tali loghi dovrebbero avere una licenza di contenuto libero compatibile con la GNU GPL v2+ per essere inseriti in tali plugin, ed invece sono sotto implicita licenza "tutti i diritti riservati".

## In sostanza
Bisognerebbe richiedere a tutti i vari IDP di rilasciare il proprio logo SPID sotto una licenza di contenuto libero compatibile con la GNU GPL v2+.

Ecco un elenco di licenze che possono essere adottate da tali IDP per proteggere il loro logo per risolvere il problema:

* [GNU General Public License v2+](https://www.gnu.org/licenses/gpl-2.0.html)
* [GNU Free Documentation License](https://www.gnu.org/copyleft/fdl.html)
* [Creative Commons BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.it)
* [Creative Commons BY](https://creativecommons.org/licenses/by/4.0/deed.it)
* [Creative Commons 0](https://creativecommons.org/publicdomain/zero/1.0/deed.it)

Come si potrebbe procede per contattare i sigoli IDP?

**Comment by umbros** [comment]
I loghi sono utilizzabili senza problematiche di licenza
