### ISSUE TITLE
Configurazione JS per parametro redirect

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-sp-access-button#6]
Non si potrebbe implementare (se non ci fosse già... però #2... :D) un'opzione JS per impostare il redirect post autenticazione, cosicchè tutti gli utilizzatori di questo bottone non debbano modificare il codice per ogni loro utilizzo (dato che l'indirizzo dove gli IDP mandano l'utente è sempre lo stesso a parte il suddetto parametro per il redirect)?

**Comment by umbros** [comment]
Il redirect post autenticazione è gestito dall'SP con il relay state. Mi spieghi meglio come lo immagini il processo?

**Comment by valerio-bozzolan** [comment]
Uhm. Non ricordo più la mia domanda quindi chiudo. Forse avevi risolto i miei dubbi.
